Mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('',include('food.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('',views.home,name='home'),
    path('item/<int:item_id>',views.detail,name='detail')
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=100)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.ImageField(upload_to='pics')

food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item

# Create your views here.
def home(request):
    items = Item.objects.all()
    return render(request,'food/index.html',{'items':items})

def detail(request,item_id):
    item = Item.objects.get(pk = item_id)
    return render(request,'food/detail.html',{'item':item})

templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodApp</title>
    <link rel="stylesheet" href="{% static 'js/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Delete Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View Item</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                </ul>
              </li>
             
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% block content %}
      

      {% endblock %}
    
  

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/food/detail.html
{% extends 'food/base.html' %}


{% block content %}
    
        <div class="col-md-9 mx-auto mt-4">
            <div class="d-flex justify-content-center mt-3">
                <div class="card" style="width: 40rem;">
                    <img style="height: 280px;" src="{{ item.item_image.url}}" class="img-fluid" alt="...">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <h5 class="card-title">{{item.item_name}}</h5>
                        <h5 class="card-title">Price: {{item.item_price}} Tk</h5>
                      </div>
                      <p>{{item.item_desc}}</p>
                      <a href="" class="btn btn-primary">Delete</a>
                    </div>
                  </div>
                 
            </div>
        </div>
  
{% endblock %}

templates/food/index.html
{% extends 'food/base.html' %}


{% block content %}
    
        <div class="col-md-9 mx-auto mt-4">
            <div class="d-flex justify-content-between mt-3">
                {% for item in items %}
                <div class="card" style="width: 28rem;">
                    <img style="height: 280px;" src="{{ item.item_image.url}}" class="img-fluid" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{item.item_name}}</h5>
                      <a href="{% url 'food:detail' item.id %}" class="btn btn-primary">Details</a>
                    </div>
                  </div>
                  {% endfor %}
            </div>
        </div>
  
{% endblock %}